artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/mashaan14/MNIST-M/blob/main/MNIST-M.zip?raw=true
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion